external_test_case_classes:
- QuickSpec
project: PlacesFinder.xcodeproj
report_exclude:
- PlacesFinderTests/Components/Sourcery/Output/**
retain_public: true
schemes:
- PlacesFinder
- PlacesFinderTests
