disabled_rules: # rule identifiers to exclude from running
  - implicit_return
  - nesting
  - trailing_comma

opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - extension_access_modifier
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_boolean
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_capture_list
  - unused_import
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition
  # Find all the available rules by running:
  # swiftlint rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - PlacesFinder/CoordiNode/Output
  - PlacesFinder/OutdatedDependencies.swift
  - PlacesFinder/Sourcery/Output
  - PlacesFinderTests/Components/Sourcery/Output
  - PlacesFinderUITests/Fakes
  - Shared/Shared/OutdatedDependencies.swift
  - Shared/Shared/Sourcery/Output
  - Shared/SharedTestComponents/Sourcery/Output

line_length: 120

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 600

function_body_length:
  warning: 60

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50

identifier_name:
  min_length: # only min_length
    error: 3 # only error

number_separator:
  minimum_length: 5
    
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
