name: PlacesFinder
options:
  bundleIdPrefix: com.justinpeckner
  transitivelyLinkDependencies: true
  groupSortPosition: top
  deploymentTarget:
    iOS: "13.0"
attributes:
   ORGANIZATIONNAME: Justin Peckner
targets:

  PlacesFinder:
    type: application
    platform: iOS
    configFiles:
      Debug: PlacesFinder/Config/xcconfig/Debug.xcconfig
      Release: PlacesFinder/Config/xcconfig/Release.xcconfig
    info:
      path: PlacesFinder/Info.plist
      properties:
        CFBundleDisplayName: PlacesFinder
        CFBundleShortVersionString: None
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.justinpeckner.PlacesFinder
            CFBundleURLSchemes: [$(URL_SCHEME)]
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        NSLocationWhenInUseUsageDescription: >-
            PlacesFinder would like to access your location when using the app to show you
            nearby places of interest.
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [
          UIInterfaceOrientationPortrait, 
          UIInterfaceOrientationPortraitUpsideDown,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight
        ]
    attributes:
      DevelopmentTeam: ER3Y6PM2YR
    sources:
      - path: PlacesFinder
    dependencies:
      - framework: Shared.framework
        implicit: true
    postCompileScripts:
      - script: |
                cd "$PROJECT_DIR"
                mint run realm/SwiftLint swiftlint
        name: SwiftLint
      
  PlacesFinderTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: PlacesFinderTests/Info.plist
    sources:
      - path: PlacesFinder
      - path: PlacesFinderTests
    dependencies:
      - framework: SharedTestComponents.framework
        implicit: true
      
  PlacesFinderIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: PlacesFinderIntegrationTests/Info.plist
    sources:
      - path: PlacesFinder
      - path: PlacesFinderIntegrationTests
    dependencies:
      - framework: SharedTestComponents.framework
        implicit: true
      
  PlacesFinderUITests:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: PlacesFinderUITests/Info.plist
    sources: PlacesFinderUITests
    dependencies:
      - target: PlacesFinder

schemes:

  PlacesFinder-Debug:
    build:
      targets:
        PlacesFinder: all
        PlacesFinderTests: [test]
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: PlacesFinderTests
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release

  PlacesFinder-Release:
    build:
      targets:
        PlacesFinder: all
        PlacesFinderTests: [test]
        PlacesFinderIntegrationTests: [test]
        PlacesFinderUITests: [test]
    run:
      config: Release
    test:
      config: Release
      targets:
        - name: PlacesFinderTests
          randomExecutionOrder: true
        - name: PlacesFinderIntegrationTests
          randomExecutionOrder: true
        - name: PlacesFinderUITests
          randomExecutionOrder: true
      environmentVariables:
        - variable: TEST_PLACE_LOOKUP_PORT
          value: $(TEST_PLACE_LOOKUP_PORT)
          isEnabled: true
        - variable: PLACE_LOOKUP_BASE_URL
          value: $(PLACE_LOOKUP_BASE_URL)
          isEnabled: true
        - variable: PLACE_LOOKUP_KEY
          value: $(PLACE_LOOKUP_KEY)
          isEnabled: true
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
