name: PlacesFinder
options:
  bundleIdPrefix: com.justinpeckner
  carthageExecutablePath: /usr/local/bin/carthage
  transitivelyLinkDependencies: true
  groupSortPosition: top
  deploymentTarget:
    iOS: "11.0"
attributes:
   ORGANIZATIONNAME: Justin Peckner
fileGroups:
  - BuildScripts
targets:

  PlacesFinder:
    type: application
    platform: iOS
    configFiles:
      Debug: PlacesFinder/Config/xcconfig/Debug.xcconfig
      Release: PlacesFinder/Config/xcconfig/Release.xcconfig
    info:
      path: PlacesFinder/Info.plist
      properties:
        CFBundleDisplayName: PlacesFinder
        CFBundleShortVersionString: None
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.justinpeckner.PlacesFinder
            CFBundleURLSchemes: [$(URL_SCHEME)]
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        NSLocationWhenInUseUsageDescription: >-
            PlacesFinder would like to access your location when using the app to show you
            nearby places of interest.
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [
          UIInterfaceOrientationPortrait, 
          UIInterfaceOrientationPortraitUpsideDown,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight
        ]
    attributes:
      DevelopmentTeam: ER3Y6PM2YR
    sources:
    - path: PlacesFinder
      excludes:
        - "Sourcery/Output/AutoMockable.generated.swift"
    dependencies:
      - framework: Shared.framework
        implicit: true
      - framework: CoordiNode.framework
        implicit: true
      - carthage: Kingfisher
      - carthage: Reachability
      - carthage: SwiftDux
      - carthage: SkeletonView
      - carthage: SnapKit
    preBuildScripts:
      - path: BuildScripts/carthage_verify.sh
        name: Carthage - Verify
    postCompileScripts:
      - script: |
                cd "$PROJECT_DIR/.."
                mint run realm/SwiftLint swiftlint
        name: SwiftLint
      
  PlacesFinderTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: PlacesFinderTests/Info.plist
    sources:
      - path: PlacesFinder/Sourcery/Output/AutoMockable.generated.swift
      - path: PlacesFinderTests
      # placeholder:PlacesFinderTests:sources:path
    dependencies:
      - target: PlacesFinder
      - framework: SharedTestComponents.framework
        implicit: true
      - framework: CoordiNodeTestComponents.framework
        implicit: true
      - carthage: SwiftDuxTestComponents
      - carthage: Nimble
      - carthage: Quick
      
  PlacesFinderIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: PlacesFinderIntegrationTests/Info.plist
    sources:
      - path: PlacesFinderIntegrationTests
      - path: PlacesFinder
    dependencies:
      - target: PlacesFinder
      - carthage: Nimble
      - carthage: Quick
      
  PlacesFinderUITests:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: PlacesFinderUITests/Info.plist
    sources: PlacesFinderUITests
    dependencies:
      - target: PlacesFinder
      - carthage: Swifter

schemes:

  PlacesFinder-Debug:
    build:
      targets:
        PlacesFinder: all
        PlacesFinderTests: [test]
      postActions:
        - script: |
                  "$PROJECT_DIR/BuildScripts/carthage_outdated_post_action.sh"
          name: Carthage - Outdated Frameworks
          settingsTarget: PlacesFinder
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: PlacesFinderTests
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release

  PlacesFinder-Release:
    build:
      targets:
        PlacesFinder: all
        PlacesFinderTests: [test]
        PlacesFinderIntegrationTests: [test]
        PlacesFinderUITests: [test]
    run:
      config: Release
    test:
      config: Release
      targets:
        - name: PlacesFinderTests
          randomExecutionOrder: true
        - name: PlacesFinderIntegrationTests
          randomExecutionOrder: true
        - name: PlacesFinderUITests
          randomExecutionOrder: true
      environmentVariables:
        - variable: TEST_PLACE_LOOKUP_PORT
          value: $(TEST_PLACE_LOOKUP_PORT)
          isEnabled: true
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
