
SHARED_ROOT = "Shared"
SHARED_PROJECT_PATH = SHARED_ROOT + "/Shared.xcodeproj"

PLACESFINDER_ROOT = "PlacesFinder"
PLACESFINDER_WORKSPACE_PATH = "PlacesFinder.xcworkspace"
PLACESFINDER_PROJECT_PATH = "PlacesFinder.xcodeproj"
PLACESFINDER_INFOPLIST_PATH = PLACESFINDER_ROOT + "/Info.plist"

BUILD_PATH = "fastlane/Build"
GYM_FOLDER_PATH = BUILD_PATH + "/gym"
